### ISSUE TITLE
Bootstrap CDN being blocked due to CORS

### ISSUE THREAD

**Issue by dospunk** [aaronduino/asciidots#60] opened 2017-11-28 21:39 UTC
In the [demo](http://ajanse.me/asciidots/demo), opening the console shows this error

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

**Comment by aaronduino** [comment] 2017-12-01 03:08
This should be fixed by 73084de770a5ea01f1c5fbf2ff48e0229b42e2ca

If you refresh your cache (in chrome: open dev tools, press & hold reload to get clear cache option), does it work?

If you can't figure out how to easily refresh your cache, try just reloading.

Thanks for the bug report, btw.

**Comment by dospunk** [comment] 2017-12-01 04:25
Turns out it was caused by the HTTPS everywhere extension

**Comment by aaronduino** [comment] 2017-12-02 02:31
Oh, hahaha.

I had the exact same problem a few months ago, but it suddenly went away one day.
After reading your comment, I now realize that it went away when I disabled https everywhere for an unrelated reason.

Thanks for the feedback.

If there is anything you recommend I do to make it work with https everywhere, feel free to respond back.

Btw, the error is likely caused by the fact that I have a GitHub.io certificate being used by ajanse.me :/

**Closed** 2017-12-02 07:31 UTC
Labels: bug, demo
